20.35 Archipelag

In [8]:
# General

In [9]:
#%%capture
#!pip install sweetviz

In [10]:
import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt
import seaborn as sns
#import sweetviz
#from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import OneHotEncoder

**Part 1. IBM HR analytics dataset EDA**

In [11]:
data4IBM=pd.read_csv("../input/ibm-hr-analytics-attrition-dataset/WA_Fn-UseC_-HR-Employee-Attrition.csv", header=0)
data4IBM.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7

In [12]:
data4IBM.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [13]:
data4IBM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [14]:
#sweetreport = sweetviz.analyze(data4IBM, target_feat="Attrition")
#sweetreport.show_html('sweetreport.html')

NameError: name 'sweetviz' is not defined

In [ ]:
corr4=data4IBM.corr()
corr4

In [ ]:
f,ax = plt.subplots(figsize=(15,15))
sns.heatmap(corr4, annot=True, linewidths=.5, fmt= '.1f',ax=ax)

In [ ]:
deep_dive1 = ['Age','Over18','Gender']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive1):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive2 = ['EducationField','Education','Department']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive2):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive3 = ['BusinessTravel', 'DistanceFromHome', 'EnvironmentSatisfaction']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive3):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive4 = ['MaritalStatus','WorkLifeBalance','OverTime']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive4):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition', palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive7 = ['StandardHours','RelationshipSatisfaction','TrainingTimesLastYear']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive7):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive5 = ['JobLevel', 'JobInvolvement', 'JobSatisfaction'] 

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive5):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive6 = ['TotalWorkingYears', 'NumCompaniesWorked', 'YearsAtCompany']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive6):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive7 = ['YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive7):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

In [ ]:
deep_dive7 = ['MonthlyIncome', 'PercentSalaryHike', 'PerformanceRating']

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(25,5))
fig.subplots_adjust(hspace=0.5, bottom=0)
for ax, catplot in zip(axes.flatten(), deep_dive7):
        sns.countplot(x=catplot, data=data4IBM, hue='Attrition',  palette="Set3", ax=ax, )
        ax.set_title(catplot.upper(), fontsize=12)
        ax.set_ylabel('Count', fontsize=12)
        ax.set_xlabel(f'{catplot} Values', fontsize=12)
        ax.legend(title='Attrition', fontsize=12)

**Part 2. Cattell's 16 personality factors dataset EDA**

In [ ]:
data16 = pd.read_csv("/kaggle/input/cattells-16-personality-factors/16PF/data.csv", sep="\t")
data16.head(10)

In [ ]:
data16.info()

In [ ]:
data16.describe()

In [ ]:
corr1=data16.corr()

corr1.style.background_gradient(cmap='coolwarm')

corr1 

#corr1.to_csv("D:\corr1.csv")

In [ ]:
f,ax = plt.subplots(figsize=(50,50))
sns.heatmap(corr1, annot=True, linewidths=.5, fmt= '.1f',ax=ax)

In [ ]:
data16['A'] = (data16['A1']+data16['A2']+data16['A3']+data16['A4']+data16['A5']+data16['A6']+data16['A7']+data16['A8']+data16['A9']+data16['A10'])/10
data16['B'] = (data16['B1']+data16['B2']+data16['B3']+data16['B4']+data16['B5']+data16['B6']+data16['B7']+data16['B8']+data16['B9']+data16['B10']+data16['B11']+data16['B12']+data16['B13'])/13
data16['C'] = (data16['C1']+data16['C2']+data16['C3']+data16['C4']+data16['C5']+data16['C6']+data16['C7']+data16['C8']+data16['C9']+data16['C10'])/10
data16['D'] = (data16['D1']+data16['D2']+data16['D3']+data16['D4']+data16['D5']+data16['D6']+data16['D7']+data16['D8']+data16['D9']+data16['D10'])/10
data16['E'] = (data16['E1']+data16['E2']+data16['E3']+data16['E4']+data16['E5']+data16['E6']+data16['E7']+data16['E8']+data16['E9']+data16['E10'])/10
data16['F'] = (data16['F1']+data16['F2']+data16['F3']+data16['F4']+data16['F5']+data16['F6']+data16['F7']+data16['F8']+data16['F9']+data16['F10'])/10
data16['G'] = (data16['G1']+data16['G2']+data16['G3']+data16['G4']+data16['G5']+data16['G6']+data16['G7']+data16['G8']+data16['G9']+data16['G10'])/10
data16['H'] = (data16['H1']+data16['H2']+data16['H3']+data16['H4']+data16['H5']+data16['H6']+data16['H7']+data16['H8']+data16['H9']+data16['H10'])/10
data16['I'] = (data16['I1']+data16['I2']+data16['I3']+data16['I4']+data16['I5']+data16['I6']+data16['I7']+data16['I8']+data16['I9']+data16['I10'])/10
data16['J'] = (data16['J1']+data16['J2']+data16['J3']+data16['J4']+data16['J5']+data16['J6']+data16['J7']+data16['J8']+data16['J9']+data16['J10'])/10
data16['K'] = (data16['K1']+data16['K2']+data16['K3']+data16['K4']+data16['K5']+data16['K6']+data16['K7']+data16['K8']+data16['K9']+data16['K10'])/10
data16['L'] = (data16['L1']+data16['L2']+data16['L3']+data16['L4']+data16['L5']+data16['L6']+data16['L7']+data16['L8']+data16['L9']+data16['L10'])/10
data16['M'] = (data16['M1']+data16['M2']+data16['M3']+data16['M4']+data16['M5']+data16['M6']+data16['M7']+data16['M8']+data16['M9']+data16['M10'])/10
data16['N'] = (data16['N1']+data16['N2']+data16['N3']+data16['N4']+data16['N5']+data16['N6']+data16['N7']+data16['N8']+data16['N9']+data16['N10'])/10
data16['O'] = (data16['O1']+data16['O2']+data16['O3']+data16['O4']+data16['O5']+data16['O6']+data16['O7']+data16['O8']+data16['O9']+data16['O10'])/10
data16['P'] = (data16['P1']+data16['P2']+data16['P3']+data16['P4']+data16['P5']+data16['P6']+data16['P7']+data16['P8']+data16['P9']+data16['P10'])/10
data16.drop(columns = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11","B12","B13","C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9", "E10", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8", "G9", "G10", "H1", "H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10", "I1", "I2", "I3", "I4", "I5", "I6", "I7", "I8", "I9", "I10", "J1", "J2", "J3", "J4", "J5", "J6", "J7", "J8", "J9", "J10", "K1", "K2", "K3", "K4", "K5", "K6", "K7", "K8", "K9", "K10", "L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", "L9", "L10", "M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10", "N1", "N2", "N3", "N4", "N5", "N6", "N7", "N8", "N9", "N10", "O1", "O2", "O3", "O4", "O5", "O6", "O7", "O8", "O9", "O10", "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10"], inplace=True) 
data16

In [ ]:
data16.describe()

In [ ]:
corr16short=data16.corr()

corr16short

In [ ]:
f,ax = plt.subplots(figsize=(15,15))
sns.heatmap(corr16short, annot=True, linewidths=.5, fmt= '.1f',ax=ax)
corr16short.style.background_gradient(cmap='coolwarm')

**Part 3. Big 5 Personality Test dataset EDA**

In [ ]:
data5 = pd.read_csv("../input/big-five-personality-test/IPIP-FFM-data-8Nov2018/data-final.csv", sep='\t')
data5.head()

In [ ]:
data5.describe()

In [ ]:
data5.info()

In [ ]:
data5.AGR7.value_counts(normalize=False).plot.bar()
plt.show
data5.AGR7.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN4.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN4.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN8.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN8.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EXT4.value_counts(normalize=False).plot.bar()
plt.show
data5.EXT4.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EST1.value_counts(normalize=False).plot.bar()
plt.show
data5.EST1.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN1.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN1.value_counts(normalize=False, ascending=False)

In [ ]:
data5.AGR2.value_counts(normalize=False).plot.bar()
plt.show
data5.AGR2.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN7.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN7.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN9.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN9.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN10.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN10.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN4.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN4.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN2.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN2.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EST5.value_counts(normalize=False).plot.bar()
plt.show
data5.EST5.value_counts(normalize=False, ascending=False)

In [ ]:
data5.AGR5.value_counts(normalize=False).plot.bar()
plt.show
data5.AGR5.value_counts(normalize=False, ascending=False)

In [ ]:
data5.AGR1.value_counts(normalize=False).plot.bar()
plt.show
data5.AGR1.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EXT8.value_counts(normalize=False).plot.bar()
plt.show
data5.EXT8.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN3.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN3.value_counts(normalize=False, ascending=False)

In [ ]:
data5.OPN7.value_counts(normalize=False).plot.bar()
plt.show
data5.OPN7.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN7.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN7.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN9.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN9.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EXT9.value_counts(normalize=False).plot.bar()
plt.show
data5.EXT9.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EST10.value_counts(normalize=False).plot.bar()
plt.show
data5.EST10.value_counts(normalize=False, ascending=False)

In [ ]:
data5.AGR5.value_counts(normalize=False).plot.bar()
plt.show
data5.AGR5.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN8.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN8.value_counts(normalize=False, ascending=False)

In [ ]:
data5.AGR3.value_counts(normalize=False).plot.bar()
plt.show
data5.AGR3.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EXT2.value_counts(normalize=False).plot.bar()
plt.show
data5.EXT2.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EST3.value_counts(normalize=False).plot.bar()
plt.show
data5.EST3.value_counts(normalize=False, ascending=False)

In [ ]:
data5.CSN6.value_counts(normalize=False).plot.bar()
plt.show
data5.CSN6.value_counts(normalize=False, ascending=False)

In [ ]:
data5.EST9.value_counts(normalize=False).plot.bar()
plt.show
data5.EST9.value_counts(normalize=False, ascending=False)

In [ ]:
data5.OPN1.value_counts(normalize=False).plot.bar()
plt.show
data5.OPN1.value_counts(normalize=False, ascending=False)